/**
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 * Runtime: 76 ms
 * Beats: 3.08%
 */
var findTheDifference = function (s, t) {
    let arr = new Array(26).fill(0);
    for (let ch of t) {
        arr[ch.charCodeAt(0) - 97]++;
    }
    for (let ch of s) {
        arr[ch.charCodeAt(0) - 97]--;
    }
    return String.fromCharCode(97 + arr.findIndex(val => val === 1));
};